spring.application.name=cadastro-cts
spring.datasource.url=jdbc:postgresql://localhost:5432/y_cadastro_cts
spring.datasource.username=postgres
spring.datasource.password=postgress
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
